language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
branches:
  only:
    - master
install:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo fmt -- --check
  - cargo clippy --tests -- -D warnings
