[package]
name = "onvif-rs"
version = "0.1.0"
authors = ["Chris Bruce <chris@lumeo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
xml-rs = "0.8.0"
yaserde = "0.3.7"
yaserde_derive = "0.3.7"
itertools = "0.8.1"
