[package]
name = "onvif-rs"
version = "0.1.0"
authors = ["Chris Bruce <chrisabruce@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
